[package]
name = "park_cli"
version = "1.0.0"
description = "Configuration-based dotfiles manager"
edition = "2021"
publish = false

[dependencies.clap]
version = "=4.0.29"
default-features = false
features = [
	"derive",
	"help",
	"std",
	"suggestions",
	"usage",
]
