[package]
name = "park"
version = "0.1.0"
authors = ["Gabriel Sanches <gabriel@gsr.dev>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
serde = { version = "1.0.133", features = ["derive"] }
tabwriter = "1.2.1"
thiserror = "1.0.26"
toml = "0.5.8"

[dev-dependencies]
indoc = "1.0.3"
maplit = "1.0.2"
pretty_assertions = "0.7.2"
