[package]
name = "park"
version = "0.1.0"
authors = ["Gabriel Sanches <gabriel@gsr.dev>"]
edition = "2018"

[dependencies]
thiserror = "1.0.26"

[dev-dependencies]
maplit = "1.0.2"
pretty_assertions = "0.7.2"
