== park

A configuration-based dotfiles manager able to organize dotfiles by symlinking them according
to a configuration file written in TOML.

image:https://builds.sr.ht/~gbrlsnchs/park.svg[builds.sr.ht status,link=https://builds.sr.ht/~gbrlsnchs/park]

=== Usage
See `park(1)` for detailed information about the command.

==== Example
Consider the following configuration file named `config.toml`:

----
base_dir = "$XDG_CONFIG_HOME"
tags = ["fontconfig"]

[targets.kakoune]
link.name = "kak"

[targets.fontconfig]
tags.all_of = ["fontconfig"]

[targets."zsh/config/zshrc"]
link.base_dir = "$HOME"
link.name = ".zshrc"

[targets.river]
tags.all_of = ["wayland", "river"]
----

In order to substitute environment variables accordingly, let's use `envsubst` and send the
output to park via stdin:

----
$ envsubst < config.toml | park
.                  root: ~/dotfiles
├── fontconfig     ~/.config/fontconfig  (READY)
├── kakoune        ~/.config/kak         (DONE)
└── zsh
    └── config
        └── zshrc  ~/.zshrc              (READY)
----

Then, in order to create their respective symlinks, we need to pass `--link` to the command:

----
$ envsubst < config.toml | park --link
----

So if all goes well, exit code is 0 and all necessary symlinks are created.

==== Tags
If you pay enough attention to the output in the previous example, `river` was not
evaluated. That's because it's guarded by two conjunctive tags (`wayland` and `river`), that is,
both tags must be passed to the command so that the target gets evaluated. In order to do so,
we need to pass those tags as arguments to park:

----
$ envsubst < config.toml | park +wayland +river
.                  root: ~/dotfiles
├── fontconfig     ~/.config/fontconfig  (DONE)
├── kakokune       ~/.config/kak         (DONE)
├── river          ~/.config/river       (READY)
└── zsh
    └── config
        └── zshrc  ~/.zshrc              (DONE)
----

==== Filtering by target name
Note that, when using tags, you need to prepend them with a plus sign. Otherwise, park would
consider arguments as _target names_, which are used for _filtering_. In the following example,
only `fontconfig` will be evaluated, since its target name is passed as argument:

----
$ envsubst < config.toml | park +wayland +river fontconfig
.                  root: ~/dotfiles
└── fontconfig     ~/.config/fontconfig  (DONE)
----

=== Configuration
See `park(5)`.

=== Contributing
mailto:~gbrlsnchs/park-dev@lists.sr.ht[Use the mailing list] to

- report issues
- request new features
- send patches
- discuss development in general

If applicable, a new ticket will be submitted by maintainers to
https://todo.sr.ht/~gbrlsnchs/park[the issue tracker] in order to track confirmed bugs or
new features.

=== Building and distributing the project
This project is built entirely in Rust. Build it as you wish for local usage, and package it
to your distro of preference in accordance with its policy on how to package Rust projects.

NOTE: `cargo build` generates shell completions for Bash, ZSH and Fish, which
are available at `target/completions`, and manpages at `target/doc` (only when
https://git.sr.ht/~sircmpwn/scdoc[`scdoc`] is available).
