= park

A configuration-based dotfiles manager able to organize dotfiles by symlinking them according
to a configuration file written in TOML.

== Usage
See `park(1)` for detailed information about the command.

=== Example
Consider the following configuration file named `config.toml`:

----
base_dir = "$XDG_CONFIG_HOME"
tags = ["fontconfig"]

[targets.kakoune]
link.name = "kak"

[targets.fontconfig]
tags.all_of = ["fontconfig"]

[targets."zsh/config/zshrc"]
link.base_dir = "$HOME"
link.name = ".zshrc"

[targets.river]
tags.all_of = ["wayland", "river"]
----

In order to substitute environment variables accordingly, let's use `envsubst` and send the
output to park via stdin:

----
$ envsubst < config.toml | park
.                 := /home/you/dotfiles
├── fontconfig    <- /home/you/.config/fontconfig (READY)
├── kakoune       <- /home/you/.config/kak        (DONE)
└── zsh
    └── config
        └── zshrc <- /home/you/.zshrc             (READY)
----

Then, in order to create their respective symlinks, we need to pass `--link` to the command:

----
$ envsubst < config.toml | park --link
----

So if all goes well, exit code is 0 and all necessary symlinks are created.

=== Tags
If you pay enough attention to the output in the previous example, `river` was not
evaluated. That's because it's guarded by two conjunctive tags (`wayland` and `river`), that is,
both tags must be passed to the command so that the target gets evaluated. In order to do so,
we need to pass those tags as arguments to park:

----
$ envsubst < config.toml | park +wayland +river
.                 := /home/you/dotfiles
├── fontconfig    <- /home/you/.config/fontconfig (DONE)
├── kakokune      <- /home/you/.config/kak        (DONE)
├── river         <- /home/you/.config/river      (READY)
└── zsh
    └── config
        └── zshrc <- /home/you/.zshrc             (DONE)
----

=== Filtering by target name
Note that, when using tags, you need to append them with a plus sign. Otherwise, park would
consider arguments as _target names_, which are used for _filtering_. In the following example,
only `fontconfig` will be evaluated, since its target name is passed as argument:

----
$ envsubst < config.toml | park fontconfig
.                 := /home/you/dotfiles
└── fontconfig    <- /home/you/.config/fontconfig (DONE)
----

== Configuration
See `park(5)`.

== Building the project
This project is built entirely in Rust, and makes no use of Cargo workspaces. Build it as you
wish for local usage, and package it to your distro of preference according to its policy on
how to package software built in Rust.

NOTE: `cargo build` generates shell completions for Bash, ZSH and Fish, which
are available at `target/completions`, and manpages at `target/doc` (only when
https://git.sr.ht/~sircmpwn/scdoc[`scdoc`] is available).
